CREATE DATABASE IF NOT EXISTS REVISTAELETRONICA;

USE REVISTAELETRONICA;

CREATE TABLE IF NOT EXISTS TB_USUARIO
(
TB_USER_ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
TB_USER_NOME VARCHAR(64) NOT NULL,
TB_USER_EMAIL VARCHAR(128) NOT NULL,
TB_USER_SENHA VARCHAR(32) NOT NULL 
);

CREATE TABLE IF NOT EXISTS TB_EVENTO
(
TB_EVENTO_ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
TB_EVENTO_NOME VARCHAR(64) NOT NULL,
TB_EVENTO_DT DATE NOT NULL,
TB_EVENTO_DONO VARCHAR(128) NOT NULL
);

 -- CADASTRAR USER 
DELIMITER $$
DROP PROCEDURE IF EXISTS CAD_USER;
CREATE PROCEDURE CAD_USER (IN CAD_NOME VARCHAR(64), IN CAD_EMAIL VARCHAR(128), IN CAD_SENHA VARCHAR(32))
BEGIN
SET @valida_user = (
SELECT COUNT(TB_USER_ID)
FROM TB_USUARIO
WHERE TB_USER_EMAIL = CAD_EMAIL 
);  
IF @valida_user = 0 THEN
INSERT INTO TB_USUARIO 
VALUES 
(
DEFAULT,
CAD_NOME,
CAD_EMAIL,
CAD_SENHA
);
SELECT '1' AS Mensagem;
ELSE
SELECT 'HÁ UM USUARIO COM ESTE EMAIL!' AS Mensagem;
END IF;
END$$
DELIMITER ;

CALL CAD_USER('abc', 'abc@gmail.com', '123');

 -- LOGAR USER
DELIMITER $$
DROP PROCEDURE IF EXISTS LOG_USER;
CREATE PROCEDURE LOG_USER (IN L_EMAIL VARCHAR(128), IN L_SENHA VARCHAR(32))
BEGIN
SET @Login_user = (
SELECT COUNT(TB_USER_ID) 
FROM TB_USUARIO 
WHERE TB_USER_EMAIL = L_EMAIL 
AND TB_USER_SENHA = L_SENHA
);
IF @Login_user = 1 THEN
SELECT '1' AS Mensagem;
ELSE 
SELECT 'Não foi possivel efetuar o Login!' AS Mensagem;
END IF;
END$$
DELIMITER ;

CALL LOG_USER ('vs@gmail.com', '123');

SELECT * FROM TB_USUARIO;

select tb_user_id from tb_usuario where tb_user_email = 'vs@gmail.com';

 -- CADASTRAR EVENTO
DELIMITER $$
DROP PROCEDURE IF EXISTS CAD_EVENTO;
CREATE PROCEDURE CAD_EVENTO (IN C_NOME VARCHAR(64), IN C_DATA DATE, IN C_DONO VARCHAR(128))
BEGIN
SET @CAD_EVE = (
SELECT COUNT(TB_USER_ID)
FROM TB_USUARIO
WHERE TB_USER_EMAIL = C_DONO
);
IF @CAD_EVE = 1 THEN
INSERT INTO TB_EVENTO
VALUES
(
DEFAULT,
C_NOME,
C_DATA,
C_DONO
);
SELECT '1' AS Mensagem;
ELSE
SELECT '2' AS Mensagem,
	   'Não foi possivel efetuar o cadastro.' AS Mensagem2;
END IF;
END$$
DELIMITER ;

CALL CAD_EVENTO ('Baile do Helipa', '2003-12-06', 'v12s@gmail.com');

SELECT * FROM TB_EVENTO;
 
SELECT * FROM TB_USUARIO WHERE TB_USER_EMAIL = 'vs@gmail.com' AND TB_USER_SENHA = '123';
 
